global:
  audit-prefix: "{{.Release.Name}}-{{.Chart.Name}}"
config:
  DB_HOST: "{{.Release.Name}}-{{.Chart.Name}}-postgres-service"
  DB_USERNAME: postgres
  DB_NAME: nav-audit
secret:
  DB_PASSWORD: cG9zdGdyZXM=
app:
  port: 8081
  image:
    url: mu7a/nav-quarkus-audit
    tag: "1.0-SNAPSHOT"
    pullPolicy: Always
database:
  port: 5432
  image:
    url: postgres
    tag: latest
    pullPolicy: IfNotPresent
  restartPolicy: Always
  replicas: 1
